# Generated by Django 2.2.2 on 2019-06-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdbapp', '0002_auto_20190614_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
